- name: Add TCP and UDP protocols
  firewalld:
    zone: public
    permanent: true
    state: enabled
    immediate: true
    protocol: "{{ item }}"
    offline: false
  loop:
    - tcp
    - udp
  become: true
  become_user: root

- name: Add TCP ports to firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
    permanent: true
    offline: false
  loop:
    - 5064
    - 5065
  become: true
  become_user: root

- name: Add UDP ports to firewall
  firewalld:
    port: "{{ item }}/udp"
    state: enabled
    immediate: true
    permanent: true
    offline: false
  loop:
    - 5064
    - 5065
  become: true
  become_user: root